set(c2_7001_DEFINES
    -DBOARD_C2_7001
    -DCUSTOM_BOARD_INC=c2_7001_config
    -DCONFIG_GPIO_AS_PINRESET
    -DCONFIG_NFCT_PINS_AS_GPIOS)
set(c2_7001_INCLUDE_DIRS
    "${SDK_ROOT}/components/boards")
